import { expect, it } from "vitest";
import baseline from "./fixtures/review-pipeline-speed/baseline.json";
import { createReviewInput } from "@/lib/crawl/agent-review-contract";
import { DEFAULT_CRAWL_SETTINGS } from "@/lib/crawl/settings-schema";
import { judge, factsFromRepoMeta, pageFactsFromDocument } from "@/lib/crawl/rules";
import type { CrawlCandidate, CrawlDocument } from "@/lib/db/schema";

// Generated by executing af50608 in a detached checkout, before the speed changes.
it.each(baseline.cases)("preserves the full baseline input and rule decision: $id", entry => {
  const candidate = { ...entry.candidate, judgedAt: new Date(entry.candidate.judgedAt), updatedAt: new Date(entry.candidate.updatedAt) } as CrawlCandidate;
  const document = { ...entry.document, fetchedAt: new Date(entry.document.fetchedAt) } as CrawlDocument;
  const now = new Date(baseline.at);
  const input = createReviewInput(candidate, document, DEFAULT_CRAWL_SETTINGS, { scan: null, observations: [] }, now);
  expect(JSON.parse(JSON.stringify(input))).toEqual(entry.input);
  expect(judge(factsFromRepoMeta(candidate.repo, document.repoMeta), pageFactsFromDocument(document), DEFAULT_CRAWL_SETTINGS, now)).toEqual(entry.verdict);
});
