import { expect, it } from "vitest";
import baseline from "./fixtures/review-pipeline-speed/baseline.json";
import { createReviewInput } from "@/lib/crawl/agent-review-contract";
import { DEFAULT_CRAWL_SETTINGS } from "@/lib/crawl/settings-schema";
import { judge, factsFromRepoMeta, pageFactsFromDocument } from "@/lib/crawl/rules";
import type { CrawlCandidate, CrawlDocument } from "@/lib/db/schema";

// Generated by executing af50608 in a detached checkout. Policy hashes intentionally changed
// when the star auto-approval threshold replaced the old upper cap; semantic inputs stay comparable.
it.each(baseline.cases)("preserves the full baseline input and rule decision: $id", entry => {
  const candidate = { ...entry.candidate, judgedAt: new Date(entry.candidate.judgedAt), updatedAt: new Date(entry.candidate.updatedAt) } as CrawlCandidate;
  const document = { ...entry.document, fetchedAt: new Date(entry.document.fetchedAt) } as CrawlDocument;
  const now = new Date(baseline.at);
  const input = createReviewInput(candidate, document, DEFAULT_CRAWL_SETTINGS, { scan: null, observations: [] }, now);
  const withoutHashes = (value: unknown) => {
    const copy = JSON.parse(JSON.stringify(value)) as Record<string, unknown>;
    delete copy.policyHash;
    delete copy.inputHash;
    return copy;
  };
  expect(withoutHashes(input)).toEqual(withoutHashes(entry.input));
  const verdict = judge(factsFromRepoMeta(candidate.repo, document.repoMeta), pageFactsFromDocument(document), DEFAULT_CRAWL_SETTINGS, now);
  const withoutRetiredStarStep = (steps: typeof verdict.trace) => steps.filter(step =>
    step.rule !== "스타 상한 이하" && step.rule !== "스타 하한 이상");
  expect({ ...verdict, trace: withoutRetiredStarStep(verdict.trace) })
    .toEqual({ ...entry.verdict, trace: withoutRetiredStarStep(entry.verdict.trace) });
});
