import{beforeAll,beforeEach,it,expect}from'vitest';import{eq,sql}from'drizzle-orm';import{db}from'@/lib/db';import{products,ogImages,productMedia,mediaAssets}from'@/lib/db/schema';import{ensureSchema,resetTables}from'./setup';
import{loadThumbnailProduct,saveThumbnail,listDueThumbnails}from'@/lib/domain/products/thumbnails/repository';import{defaultThumbnail}from'@/lib/domain/products/thumbnails/images';
beforeAll(ensureSchema);beforeEach(resetTables);
async function fixture(){await db.insert(products).values({slug:'image-test',url:'https://test.example',name:'Test',tagline:'A useful product',description:'Description',category:'Dev',status:'seeded',source:'crawler',verifyToken:'v',editTokenHash:'e',repoUrl:'https://github.com/acme/app'});return (await loadThumbnailProduct('image-test'))!;}
it('atomically stores a default with provenance and schedules an upgrade retry',async()=>{const p=await fixture();expect(await listDueThumbnails(6)).toHaveLength(1);expect(await saveThumbnail(p,{...await defaultThumbnail(p.name),kind:'default',sourceUrl:null,errors:['timeout']})).toBe(true);const s=await db.query.productThumbnailState.findFirst();expect(s?.kind).toBe('default');expect(s?.nextAttemptAt).toBeInstanceOf(Date);expect(await listDueThumbnails(6)).toHaveLength(0);expect(await db.select().from(ogImages)).toHaveLength(1);});
it('does not overwrite an image installed while a download is in flight',async()=>{const p=await fixture();await db.update(products).set({ogImage:'/maker.png'}).where(eq(products.slug,p.slug));expect(await saveThumbnail(p,{...await defaultThumbnail(p.name),kind:'github_avatar',sourceUrl:'https://github.com/acme.png',errors:[]})).toBe(false);expect(await db.select().from(ogImages)).toHaveLength(0);});
it('rejects stale URL/name edits and never downgrades a previous successful image',async()=>{let p=await fixture();await db.update(products).set({updatedAt:sql`now()+interval '1 second'`,name:'Changed'}).where(eq(products.slug,p.slug));expect(await saveThumbnail(p,{...await defaultThumbnail(p.name),kind:'default',sourceUrl:null,errors:[]})).toBe(false);p=(await loadThumbnailProduct(p.slug))!;await saveThumbnail(p,{...await defaultThumbnail(p.name),kind:'site_icon',sourceUrl:'https://test.example/icon.png',errors:[]});p=(await loadThumbnailProduct(p.slug))!;await saveThumbnail(p,{...await defaultThumbnail(p.name),kind:'default',sourceUrl:null,errors:['timeout']});expect((await db.query.productThumbnailState.findFirst())?.kind).toBe('site_icon');expect((await db.query.productThumbnailState.findFirst())?.lastError).toBe('timeout');});
it('protects maker media and its product even if there is no OG image',async()=>{const p=await fixture();const data=Buffer.from('test');await db.insert(mediaAssets).values({hash:'a'.repeat(64),webData:data,thumbnailData:data,width:32,height:32,thumbnailWidth:32,thumbnailHeight:32,mimeType:'image/webp',webSize:4,thumbnailSize:4});await db.insert(productMedia).values({slug:p.slug,sourceUrl:'https://test.example/screen.png',assetHash:'a'.repeat(64)});expect(await listDueThumbnails(6)).toHaveLength(0);expect(await saveThumbnail(p,{...await defaultThumbnail(p.name),kind:'default',sourceUrl:null,errors:[]})).toBe(false);});
it('retries a due default and upgrades it to OG with no further fallback retry',async()=>{
 const p=await fixture();await saveThumbnail(p,{...await defaultThumbnail(p.name),kind:'default',sourceUrl:null,errors:['timeout']});
 await db.execute(sql`update product_thumbnail_state set next_attempt_at=now()-interval '1 second' where slug=${p.slug}`);
 expect(await listDueThumbnails(6)).toEqual([p.slug]);
 const current=(await loadThumbnailProduct(p.slug))!;
 expect(await saveThumbnail(current,{...await defaultThumbnail(p.name),kind:'og',sourceUrl:'https://test.example/og.png',errors:[]})).toBe(true);
 const state=await db.query.productThumbnailState.findFirst();expect(state).toMatchObject({kind:'og',attempts:2,nextAttemptAt:null,lastError:null});
 expect((await loadThumbnailProduct(p.slug))?.ogImage).toContain('thumbnail=og');expect(await listDueThumbnails(6)).toEqual([]);
});
